CREATE TABLE PLAYER(
  	 ID INT AUTO_INCREMENT,
	 USER_NAME VARCHAR(50) NOT NULL,
	 FIRST_NAME VARCHAR(50),
	 LAST_NAME VARCHAR(50),
	 EMAIL VARCHAR(70) NOT NULL,
	 PASSWORD VARCHAR(150) NOT NULL,
	 DOB DATE,
	 CREATED_ON TIMESTAMP NOT NULL,
	 LAST_LOGGED_ON TIMESTAMP
);